name: Test InfinityFree FTP Connection

on:
  workflow_dispatch: # run manually from GitHub Actions

jobs:
  ftp-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test FTP connection
        run: |
          sudo apt-get update
          sudo apt-get install -y ftp
          echo "open ftpupload.net" > ftp.txt
          echo "if0_39705033" >> ftp.txt
          echo "ragulgamer27" >> ftp.txt
          echo "quit" >> ftp.txt
          ftp -n < ftp.txt
