name: Deploy to InfinityFree

on:
  push:
    branches:
      - master  # change to 'main' if your default branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload files to InfinityFree
        run: |
          lftp -u "${{ secrets.FTP_USER }}","${{ secrets.FTP_PASSWORD }}" ftpupload.net <<EOF
          set ftp:ssl-allow no
          set ftp:passive-mode on
          mirror -R ./ /htdocs/
          bye
          EOF
