name: 🚀 Deploy to https://test-github.free.nf/

on:
  workflow_dispatch: # Uncomment below to deploy on push instead
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy to your_domain_name
    runs-on: ubuntu-latest
run-name: 
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net # Change if using another host
          username: ${{ secrets.FTP_NAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/ # Replace with your correct path
          retries: 3
          retryDelay: 10
